var defenceAll = `<div id='g-zmievi-valy-box' class='ai2html'>
	<!-- Generated by ai2html v0.64 - 2017-06-05 - 00:33 -->
	<!-- ai file: zmievi-valy -->

	<style type='text/css' media='screen,print'>
		.g-artboard {
			margin:0 auto;
		}
	</style>


	<!-- Artboard: Artboard_1 -->
	<div id='g-zmievi-valy-Artboard_1' class='g-artboard g-artboard-v3 ' data-min-width='1110'>
		<style type='text/css' media='screen,print'>
			#g-zmievi-valy-Artboard_1{
				position:relative;
				overflow:hidden;
				width:1110px;
			}
			.g-aiAbs{
				position:absolute;
			}
			.g-aiImg{
				display:block;
				width:100% !important;
			}
			#g-zmievi-valy-Artboard_1 p{
				font-family:'Open Sans',sans-serif;
				font-size:13px;
				line-height:18px;
				margin:0;
			}
			#g-zmievi-valy-Artboard_1 .g-aiPstyle0 {
				font-size:36px;
				line-height:43px;
				color:#3a3f4a;
				font-weight:700;
			}
			#g-zmievi-valy-Artboard_1 .g-aiPstyle1 {
				font-size:16px;
				line-height:19px;
				color:#3a3f4a;
				font-style:italic;
			}
			#g-zmievi-valy-Artboard_1 .g-aiPstyle2 {
				font-size:14px;
				line-height:17px;
				color:#b2b2b2;
			}
			#g-zmievi-valy-Artboard_1 .g-aiPstyle3 {
				font-size:12px;
				line-height:14px;
				color:#b2b2b2;
			}
			#g-zmievi-valy-Artboard_1 .g-aiPstyle4 {
				font-family:arial,helvetica,sans-serif;
				font-size:12px;
				line-height:14px;
				font-style:italic;
				color:#bbc0bf;
			}
			.g-aiPtransformed p { white-space: nowrap; }
		</style>
		<div id='g-zmievi-valy-Artboard_1-graphic'>
			<img id='g-ai0-0'
				class='g-aiImg'
				src='img/ai/ai2html-output/zmievi-valy-Artboard_1.png'
				/>
			<div id='g-ai0-1' class='g-Layer_1 g-aiAbs' style='top:6.4989%;left:75.3987%;width:21.0614%;'>
				<p class='g-aiPstyle0'>Змієві вали</p>
			</div>
			<div id='g-ai0-2' class='g-Layer_1 g-aiAbs' style='top:13.6168%;left:78.1427%;width:16.9763%;'>
				<p class='g-aiPstyle1'>вали</p>
			</div>
			<div id='g-ai0-3' class='g-Layer_1 g-aiAbs' style='top:17.0211%;left:78.1399%;width:16.9763%;'>
				<p class='g-aiPstyle1'>збережені ділянки</p>
			</div>
			<div id='g-ai0-4' class='g-Layer_1 g-aiAbs' style='top:20.4253%;left:78.1427%;width:16.9763%;'>
				<p class='g-aiPstyle1'>городища в лінії валів</p>
				<p>&nbsp;</p>
			</div>
			<div id='g-ai0-5' class='g-Layer_1 g-aiAbs' style='top:24.6032%;left:44.7567%;width:5.6615%;'>
				<p class='g-aiPstyle2'>Київ</p>
			</div>
			<div id='g-ai0-6' class='g-Layer_1 g-aiAbs' style='top:30.0189%;left:1.3322%;width:9.4505%;'>
				<p class='g-aiPstyle3'>Житомир</p>
			</div>
			<div id='g-ai0-7' class='g-Layer_1 g-aiAbs' style='top:60.8116%;left:35.1319%;width:9.4505%;'>
				<p class='g-aiPstyle3'>Біла Церква</p>
			</div>
			<div id='g-ai0-8' class='g-Layer_1 g-aiAbs' style='top:84.0221%;left:70.9028%;width:9.4505%;'>
				<p class='g-aiPstyle3'>Черкаси</p>
			</div>
			<div id='g-ai0-9' class='g-Layer_1 g-aiAbs' style='top:95.0084%;left:1.5232%;'>
				<p class='g-aiPstyle4'>25 км</p>
			</div>
		</div>
	</div>


	<!-- End ai2html - 2017-06-05 - 00:33 -->
</div>`


var defenceAllMob =`<div id='g-zmievi-valy-mob-box' class='ai2html'>
	<!-- Generated by ai2html v0.64 - 2017-06-04 - 09:05 -->
	<!-- ai file: zmievi-valy-mob -->

	<style type='text/css' media='screen,print'>
		.g-artboard {
			margin:0 auto;
		}
	</style>


	<!-- Artboard: Artboard_1 -->
	<div id='g-zmievi-valy-mob-Artboard_1' class='g-artboard g-artboard-v3 ' data-min-width='300'>
		<style type='text/css' media='screen,print'>
			#g-zmievi-valy-mob-Artboard_1{
				position:relative;
				overflow:hidden;
				width:300px;
			}
			.g-aiAbs{
				position:absolute;
			}
			.g-aiImg{
				display:block;
				width:100% !important;
			}
			#g-zmievi-valy-mob-Artboard_1 p{
				font-family:'Open Sans',sans-serif;
				font-size:13px;
				line-height:18px;
				margin:0;
			}
			#g-zmievi-valy-mob-Artboard_1 .g-aiPstyle0 {
				font-size:12px;
				line-height:17px;
				color:#3a3f4a;
				font-weight: bold;
			}
			#g-zmievi-valy-mob-Artboard_1 .g-aiPstyle1 {
				font-size:8px;
				line-height:10px;
				color:#3a3f4a;
				font-style: italic;
			}
			#g-zmievi-valy-mob-Artboard_1 .g-aiPstyle2 {
				font-size:8px;
				line-height:10px;
				color:#b2b2b2;
			}
			#g-zmievi-valy-mob-Artboard_1 .g-aiPstyle3 {
				font-family:arial,helvetica,sans-serif;
				font-size:6px;
				line-height:7px;
				font-style:italic;
				color:#bbc0bf;
			}
			.g-aiPtransformed p { white-space: nowrap; }
		</style>
		<div id='g-zmievi-valy-mob-Artboard_1-graphic'>
			<img id='g-ai0-0'
				class='g-aiImg'
				src='img/ai/ai2html-output/zmievi-valy-mob-Artboard_1.png'
				/>
			<div id='g-ai0-1' class='g-Layer_1 g-aiAbs' style='top:2.3529%;left:68.7191%;width:39.2008%;'>
				<p class='g-aiPstyle0'>Змієві вали</p>
			</div>
			<div id='g-ai0-2' class='g-Layer_1 g-aiAbs' style='top:12.9412%;left:72%;width:20.1591%;'>
				<p class='g-aiPstyle1'>вали</p>
			</div>
			<div id='g-ai0-3' class='g-Layer_1 g-aiAbs' style='top:18.8235%;left:71.9948%;width:25.6667%;'>
				<p class='g-aiPstyle1'>збережені ділянки</p>
			</div>
			<div id='g-ai0-4' class='g-Layer_1 g-aiAbs' style='top:18.8235%;left:43.0861%;width:9.2472%;'>
				<p class='g-aiPstyle2'>Київ</p>
			</div>
			<div id='g-ai0-5' class='g-Layer_1 g-aiAbs' style='top:24.7059%;left:72%;width:18.8257%;'>
				<p class='g-aiPstyle1'>городища</p>
			</div>
			<div id='g-ai0-6' class='g-Layer_1 g-aiAbs' style='top:55.8824%;left:33.2701%;width:17.0632%;'>
				<p class='g-aiPstyle2'>Біла Церква</p>
			</div>
			<div id='g-ai0-7' class='g-Layer_1 g-aiAbs' style='top:83.5294%;left:65%;width:15.6227%;'>
				<p class='g-aiPstyle2'>Черкаси</p>
			</div>
			<div id='g-ai0-8' class='g-Layer_1 g-aiAbs' style='top:94.7059%;left:1.1629%;'>
				<p class='g-aiPstyle3'>25 км</p>
			</div>
		</div>
	</div>


	<!-- End ai2html - 2017-06-04 - 09:05 -->
</div>`

var pereyaslav = `<svg version="1.1" id="Layer_1" class="svgmap" viewBox="0 0 1279 696">
<style type="text/css">
	.st0{opacity:0.15;}
	.st1{fill:#FFFFFF;}
	.st2{opacity:0.5;}
	.st3{fill:none;stroke:#FFFFFF;stroke-width:3;stroke-miterlimit:10;}
	.st4{fill:none;}
	.st5{font-family:'Open Sans', sans-serif;}
	.st6{font-size:16px;}
</style>
<g class="st0">
	<path class="st1" d="M733.4,322.6c35-21.6,67.1-47.3,99.6-72.5c86.7-67.3,176.1-131,265.5-194.6c30.3-21.6,91.2-37.5,103-40
		c11.4-2.4,40.3-4.3,36.8,27.7c-1.3,12.2-15.2,17.8-26.9,21.4C1130,89.1,1067.9,153,1003,207.8c-52.4,44.2-108.7,83.6-164.8,123
		c-117.7,82.3-235.2,179.7-352.8,262C412.9,643.6,340,694.6,260.9,734.5c-12.1,6.1-24.9,12.1-38.4,12.2
		c-13.6,0.2-28.2-7.1-32.2-20.1c-4.7-14.8,3.1-32.5,15.5-41.8C270.5,636.5,604,427.6,733.4,322.6"/>
</g>
<g class="st2">
	<path class="st3" d="M733.4,319.6c35-21.6,67.1-47.3,99.6-72.5c86.7-67.3,176.1-131,265.5-194.6c30.3-21.6,91.2-37.5,103-40
		c11.4-2.4,40.3-4.3,36.8,27.7c-1.3,12.2-15.2,17.8-26.9,21.4C1130,86.1,1067.9,150,1003,204.8c-52.4,44.2-108.7,83.6-164.8,123
		c-117.7,82.3-235.2,179.7-352.8,262C412.9,640.6,340,691.6,260.9,731.5c-12.1,6.1-24.9,12.1-38.4,12.2
		c-13.6,0.2-28.2-7.1-32.2-20.1c-4.7-14.8,3.1-32.5,15.5-41.8C270.5,633.5,604,424.6,733.4,319.6"/>
</g>
<rect x="604" y="276" class="st4" width="83" height="18"/>
<text transform="matrix(1 0 0 1 604 288.7798)" class="st1 st5 st6">Лінія валу</text>
<g>
	<g>
		<g>
			<path class="st1" d="M686.6,285.9c3.5-0.7,7-0.9,10.6-0.5c3.5,0.4,7,1.3,10.1,3s5.8,4,7.9,6.9l1.4,2.2l1.1,2.4
				c0.3,0.8,0.6,1.7,0.9,2.5c0.1,0.2,0.2,0.4,0.2,0.6l0.1,0.3v0.2l-2.8,0.7c0.7,0.7,1.5,1.4,2.1,2.2c0.6,0.8,1.3,1.7,1.9,2.6
				c0.4-1,0.9-2,1.3-3.1c0.4-1.1,0.7-2.2,1-3.3l-2.8,0.7v-0.2l-0.1-0.3c0-0.2-0.1-0.4-0.2-0.7c-0.3-0.9-0.6-1.7-0.9-2.6l-1.2-2.5
				l-1.4-2.3c-2.1-3-4.9-5.4-8.1-7.1c-3.2-1.7-6.8-2.7-10.4-3.1c-3.6-0.4-7.2-0.1-10.8,0.5L686.6,285.9z"/>
		</g>
	</g>
</g>
</svg>`


var kruglyk = ` <svg version="1.1" id="Layer_1" class="svgmap" viewBox="0 0 1279 696">
<style type="text/css">
	.kst0{opacity:0.5;}
	.kst1{fill:none;stroke:#FFFFFF;stroke-width:3;stroke-miterlimit:10;}
	.kst2{opacity:0.15;}
	.kst3{fill:#FFFFFF;}
	.kst4{fill:none;}
	.kst5{font-family:'Open Sans', sans-serif;}
	.kst6{font-size:16px;}
</style>
<g class="kst0">
	<path class="kst1" d="M478,217.5c30.8,27.2,153,88,237,105c194.7,39.4,372.8,253.5,398,276c28,25,85,62.4,39,107
		c-32,31-127.2-48.8-134-59c-35-24-71.7-76.8-143-123c-31-29-185.8-99.3-268-121c-53-14-139.1-49.3-252-138
		c-69.6-54.6-139-143-206.4-224.7c-9.3-9.8-18.8-20.3-22.8-33.2c-4.1-13,8.6-36,19.9-43.6c12.8-8.8,32-6.5,44.5,2.7
		C255.2,13.6,478,217.5,478,217.5z"/>
</g>
<g class="kst2">
	<path class="kst3" d="M475,217.5c30.8,27.2,153,88,237,105c194.7,39.4,372.8,253.5,398,276c28,25,85,62.4,39,107
		c-32,31-127.2-48.8-134-59c-35-24-71.7-76.8-143-123c-31-29-185.8-99.3-268-121c-53-14-139.1-49.3-252-138
		c-69.6-54.6-139-143-206.4-224.7c-9.3-9.8-18.8-20.3-22.8-33.2c-4.1-13,8.6-36,19.9-43.6c12.8-8.8,32-6.5,44.5,2.7
		C252.2,13.6,475,217.5,475,217.5z"/>
</g>
<rect x="546" y="201" class="kst4" width="83" height="18"/>
<text transform="matrix(1 0 0 1 565 218.7798)" class="kst3 kst5 kst6">Лінія валу</text>
<g>
	<g>
		<g>
			<path class="kst3" d="M559.4,210c-3.6-0.6-7.2-0.9-10.8-0.5c-3.6,0.4-7.2,1.4-10.4,3.1c-3.2,1.7-6,4.1-8.1,7.1l-1.4,2.3l-1.2,2.5
				c-0.3,0.9-0.6,1.7-0.9,2.6c-0.1,0.3-0.2,0.5-0.2,0.7l-0.1,0.3v0.2l-2.8-0.7c0.3,1.1,0.6,2.2,1,3.3c0.4,1.1,0.9,2.1,1.3,3.1
				c0.6-0.9,1.3-1.8,1.9-2.6c0.6-0.8,1.4-1.5,2.1-2.2l-2.8-0.7v-0.2l0.1-0.3c0-0.2,0.1-0.4,0.2-0.6c0.3-0.8,0.6-1.7,0.9-2.5l1.1-2.4
				l1.4-2.2c2.1-2.9,4.8-5.2,7.9-6.9s6.6-2.6,10.1-3c3.6-0.4,7.1-0.2,10.6,0.5L559.4,210z"/>
		</g>
	</g>
</g>
</svg>`


var triangles = `<div id='g-triangles-box' class='ai2html'>
	<!-- Generated by ai2html v0.64 - 2017-06-06 - 23:58 -->
	<!-- ai file: triangles -->

	<style type='text/css' media='screen,print'>
		.g-artboard {
			margin:0 auto;
		}
	</style>


	<!-- Artboard: Artboard_1 -->
	<div id='g-triangles-Artboard_1' class='g-artboard g-artboard-v3 ' data-min-width='1110'>
		<style type='text/css' media='screen,print'>
			#g-triangles-Artboard_1{
				position:relative;
				overflow:hidden;
				width:1110px;
			}
			.g-aiAbs{
				position:absolute;
			}
			.g-aiImg{
				display:block;
				width:100% !important;
			}
			#g-triangles-Artboard_1 p{
				font-family:'Open Sans',sans-serif;
				font-size:13px;
				line-height:18px;
				margin:0;
			}
			#g-triangles-Artboard_1 .g-aiPstyle0 {
				font-size:36px;
				line-height:40px;
				color:#3a3f4a;
				font-weight:bold;
			}
			#g-triangles-Artboard_1 .g-aiPstyle1 {
				font-size:17px;
				line-height:20px;
				color:#3a3f4a;
				font-decoration: italic;
			}
			#g-triangles-Artboard_1 .g-aiPstyle2 {
				font-size:14px;
				line-height:17px;
				color:#b2b2b2;
			}
			#g-triangles-Artboard_1 .g-aiPstyle3 {
				font-size:12px;
				line-height:14px;
				color:#b2b2b2;
			}
			#g-triangles-Artboard_1 .g-aiPstyle4 {
				font-family:arial,helvetica,sans-serif;
				font-size:12px;
				line-height:14px;
				font-style:italic;
				color:#bbc0bf;
			}
			.g-aiPtransformed p { white-space: nowrap; }
		</style>
		<div id='g-triangles-Artboard_1-graphic'>
			<img id='g-ai0-0'
				class='g-aiImg'
				src='img/ai/ai2html-output/triangles-Artboard_1.png'
				/>
			<div id='g-ai0-1' class='g-Layer_1 g-aiAbs' style='top:15.8314%;left:77.2151%;width:27.3259%;'>
				<p class='g-aiPstyle0'>Київські трикутники</p>
			</div>
			<div id='g-ai0-2' class='g-Layer_1 g-aiAbs' style='top:30.4963%;left:79.8761%;width:16.9763%;'>
				<p class='g-aiPstyle1'>вали</p>
			</div>
			<div id='g-ai0-3' class='g-Layer_1 g-aiAbs' style='top:34.3292%;left:79.7375%;width:16.9763%;'>
				<p class='g-aiPstyle1'>умовні трикутники</p>
			</div>
			<div id='g-ai0-4' class='g-Layer_1 g-aiAbs' style='top:36.6622%;left:45.9423%;width:5.6615%;'>
				<p class='g-aiPstyle2'>Київ</p>
			</div>
			<div id='g-ai0-5' class='g-Layer_1 g-aiAbs' style='top:48.3275%;left:1.9896%;width:9.4505%;'>
				<p class='g-aiPstyle3'>Житомир</p>
			</div>
			<div id='g-ai0-6' class='g-Layer_1 g-aiAbs' style='top:75.6575%;left:36.3175%;width:9.4505%;'>
				<p class='g-aiPstyle3'>Біла Церква</p>
			</div>
			<div id='g-ai0-7' class='g-Layer_1 g-aiAbs' style='top:94.8218%;left:1.9669%;'>
				<p class='g-aiPstyle4'>25 км</p>
			</div>
		</div>
	</div>


	<!-- End ai2html - 2017-06-06 - 23:58 -->
</div>`



var trianglesMob = `<div id='g-triangles-mob-box' class='ai2html'>
	<!-- Generated by ai2html v0.64 - 2017-06-07 - 00:05 -->
	<!-- ai file: triangles-mob -->

	<style type='text/css' media='screen,print'>
		.g-artboard {
			margin:0 auto;
		}
	</style>


	<!-- Artboard: Artboard_1 -->
	<div id='g-triangles-mob-Artboard_1' class='g-artboard g-artboard-v3 ' data-min-width='300'>
		<style type='text/css' media='screen,print'>
			#g-triangles-mob-Artboard_1{
				position:relative;
				overflow:hidden;
				width:300px;
			}
			.g-aiAbs{
				position:absolute;
			}
			.g-aiImg{
				display:block;
				width:100% !important;
			}
			#g-triangles-mob-Artboard_1 p{
				font-family:'Open Sans',sans-serif;
				font-size:13px;
				line-height:18px;
				margin:0;
			}
			#g-triangles-mob-Artboard_1 .g-aiPstyle0 {
				font-size:12px;
				line-height:14px;
				color:#3a3f4a;
				font-weight: 700;
			}
			#g-triangles-mob-Artboard_1 .g-aiPstyle1 {
				font-size:8px;
				line-height:10px;
				color:#3a3f4a;
				font-style:  italic;
			}
			#g-triangles-mob-Artboard_1 .g-aiPstyle2 {
				font-size:8px;
				line-height:10px;
				color:#b2b2b2;
			}
			#g-triangles-mob-Artboard_1 .g-aiPstyle3 {
				font-size:8px;
				line-height:8px;
				text-align:center;
				color:#b2b2b2;
			}
			#g-triangles-mob-Artboard_1 .g-aiPstyle4 {
				font-family:arial,helvetica,sans-serif;
				font-size:7px;
				line-height:8px;
				font-style:italic;
				color:#bbc0bf;
			}
			.g-aiPtransformed p { white-space: nowrap; }
		</style>
		<div id='g-triangles-mob-Artboard_1-graphic'>
			<img id='g-ai0-0'
				class='g-aiImg'
				src='img/ai/ai2html-output/triangles-mob-Artboard_1.png'
				/>
			<div id='g-ai0-1' class='g-Layer_1 g-aiAbs' style='top:14.7059%;left:69.3613%;width:36.8282%;'>
				<p class='g-aiPstyle0'>Київські трикутники</p>
			</div>
			<div id='g-ai0-2' class='g-Layer_1 g-aiAbs' style='top:31.1765%;left:72.6644%;width:17.669%;'>
				<p class='g-aiPstyle1'>вали</p>
			</div>
			<div id='g-ai0-3' class='g-Layer_1 g-aiAbs' style='top:32.3529%;left:44.9686%;width:7.6981%;'>
				<p class='g-aiPstyle2'>Київ</p>
			</div>
			<div id='g-ai0-4' class='g-Layer_1 g-aiAbs' style='top:36.4706%;left:71.7412%;width:25.3356%;'>
				<p class='g-aiPstyle1'>умовні трикутники</p>
			</div>
			<div id='g-ai0-5' class='g-Layer_1 g-aiAbs' style='top:74.7059%;left:32.7168%;width:11.8998%;margin-left:-5.9499%;'>
				<p class='g-aiPstyle3'>Біла Церква</p>
			</div>
			<div id='g-ai0-6' class='g-Layer_1 g-aiAbs' style='top:93.5294%;left:66.6812%;width:11.6521%;'>
				<p class='g-aiPstyle2'>Черкаси</p>
			</div>
			<div id='g-ai0-7' class='g-Layer_1 g-aiAbs' style='top:93.5294%;left:1.276%;'>
				<p class='g-aiPstyle4'>25 км</p>
			</div>
		</div>
	</div>


	<!-- End ai2html - 2017-06-07 - 00:05 -->
</div>`


var khodosivka = `<svg version="1.1" id="Layer_1" class="svgmap" viewBox="0 0 1279 696">
<style type="text/css">
	.hst0{opacity:0.5;}
	.hst1{fill:none;stroke:#FFFFFF;stroke-width:3;stroke-miterlimit:10;}
	.hst2{opacity:0.15;}
	.hst3{fill:#FFFFFF;}
	.hst4{fill:none;}
	.hst5{enable-background:new    ;}
	.hst6{font-family:'Opens Sans', sans-serif;}
	.hst7{font-size:16px;}
</style>
<g class="hst0">
	<path class="hst1" d="M881,307.5c34,6,84.3,13.9,109,83c15,42-84.5,303.5-94,336c-14,48-27,70-56,114c-24.5,37.2-55,39-55,39
		c-53-14-339.1-67.3-452-156c-69.6-54.6,30.8-193.1,37-207c8-18,107-211,113-229c3-22,38.5-84.4,49-93c28-23,64.5-15.2,77-6
		C674,236.4,881,307.5,881,307.5z"/>
</g>
<g class="hst2">
	<path class="hst3" d="M881,307.5c34,6,84.3,13.9,109,83c15,42-84.5,303.5-94,336c-14,48-27,70-56,114c-24.5,37.2-55,39-55,39
		c-53-14-339.1-67.3-452-156c-69.6-54.6,30.8-193.1,37-207c8-18,107-211,113-229c3-22,38.5-84.4,49-93c28-23,64.5-15.2,77-6
		C674,236.4,881,307.5,881,307.5z"/>
</g>
<g class="hst0">
	<path class="hst1" d="M1321-53c13-0.5,52.5-14.1,104,34.5c31.3,29.5,82.4,489.9,90,520.6c11.2,45.4,11.2,68.7,8.7,116.4
		c-2.1,40.3-1.3,46.5-13.3,53.3c-42.7,24-238.4,78.6-368.4,46.7c-80.2-19.6-94.4-167-96-181c-2-18.1-25.4-232.7-29-250
		c-7.8-19.5-27.7-293.1-23.4-304.3c11.4-29.8,43.8-36.9,57.9-33.9C1124.9-34.9,1321-53,1321-53z"/>
</g>
<g class="hst2">
	<path class="hst3" d="M1321-53c13-0.5,52.5-14.1,104,34.5c31.3,29.5,82.4,489.9,90,520.6c11.2,45.4,11.2,68.7,8.7,116.4
		c-2.1,40.3-1.3,46.5-13.3,53.3c-42.7,24-238.4,78.6-368.4,46.7c-80.2-19.6-94.4-167-96-181c-2-18.1-25.4-232.7-29-250
		c-7.8-19.5-27.7-293.1-23.4-304.3c11.4-29.8,43.8-36.9,57.9-33.9C1124.9-34.9,1321-53,1321-53z"/>
</g>
<g class="st2">
	<path class="hst3" d="M-145,679.5c30.8,27.2,153,88,237,105c194.7,39.4,372.8,253.5,398,276c28,25,85,62.4,39,107
		c-32,31-127.2-48.8-134-59c-35-24-71.7-76.8-143-123c-31-29-185.8-99.3-268-121c-53-14-139.1-49.3-252-138
		c-69.6-54.6-139-143-206.4-224.7c-9.3-9.8-18.8-20.3-22.8-33.2c-4.1-13,8.6-36,19.9-43.6c12.8-8.8,32-6.5,44.5,2.7
		C-367.8,475.6-145,679.5-145,679.5z"/>
</g>
<rect x="546" y="201" class="st4" width="83" height="18"/>
<text transform="matrix(1 0 0 1 670 155.7798)" class="st5"><tspan x="0" y="0" class="hst3 hst6 hst7">Залишки </tspan><tspan x="0" y="21.6" class="hst3 hst6 hst7">городища</tspan></text>
<g>
	<g>
		<g>
			<path class="hst3" d="M658.4,157c-3.6-0.6-7.2-0.9-10.8-0.5c-3.6,0.4-7.2,1.4-10.4,3.1c-3.2,1.7-6,4.1-8.1,7.1l-1.4,2.3l-1.2,2.5
				c-0.3,0.9-0.6,1.7-0.9,2.6c-0.1,0.3-0.2,0.5-0.2,0.7l-0.1,0.3v0.2l-2.8-0.7c0.3,1.1,0.6,2.2,1,3.3c0.4,1.1,0.9,2.1,1.3,3.1
				c0.6-0.9,1.3-1.8,1.9-2.6c0.6-0.8,1.4-1.5,2.1-2.2l-2.8-0.7v-0.2l0.1-0.3c0-0.2,0.1-0.4,0.2-0.6c0.3-0.8,0.6-1.7,0.9-2.5l1.1-2.4
				l1.4-2.2c2.1-2.9,4.8-5.2,7.9-6.9s6.6-2.6,10.1-3c3.6-0.4,7.1-0.2,10.6,0.5L658.4,157z"/>
		</g>
	</g>
</g>
<text transform="matrix(1 0 0 1 896 72.7798)" class="hst3 hst6 hst7">Лінія валу</text>
<g>
	<g>
		<g>
			<path class="hst3" d="M943.8,90.6c0.8,3.6,1.9,7,3.7,10.2c1.8,3.2,4.1,6.1,6.9,8.4c2.8,2.3,6.1,4,9.7,4.8l2.7,0.4l2.8,0.1
				c0.9-0.1,1.8-0.1,2.7-0.2c0.3,0,0.5,0,0.7-0.1l0.3,0l0.2-0.1l0.4,2.9c0.9-0.7,1.8-1.4,2.7-2.2c0.9-0.8,1.6-1.6,2.4-2.4
				c-1.1-0.2-2.2-0.5-3.1-0.8c-1-0.2-1.9-0.7-2.8-1.1l0.4,2.9l-0.2,0.1l-0.3,0c-0.2,0.1-0.4,0.1-0.6,0c-0.9,0-1.8,0.1-2.7,0.1
				l-2.6-0.1l-2.6-0.4c-3.5-0.8-6.6-2.4-9.4-4.6c-2.8-2.2-4.9-5.1-6.6-8.2c-1.8-3.2-2.9-6.5-3.6-10L943.8,90.6z"/>
		</g>
	</g>
</g>
</svg>`



$("#defenceAll").append(defenceAll);
$("#defenceAllMob").append(defenceAllMob);
$("#triangles").append(triangles);
$("#trianglesMob").append(trianglesMob);
$("#pereyaslav").append(pereyaslav);
$("#kruglyk").append(kruglyk);
$("#khodosivka").append(khodosivka);



